---
editor_options: 
  chunk_output_type: console
---

# Comparing ecological outcomes across parameter combinations

![**Rapid changes in ecological outcomes following pathogen introduction.** The introduction of the infectious pathogen leads to rapid evolutionary changes in movement strategies (see Figures 1 and 4; main text) across most combinations of landscape productivity and infection cost. In all combinations where there is rapid evolutionary shift in social-movement strategies, there is a similar change in the population's ecological outcomes: more movement, less intake, and fewer associations. Each subplot in each panel shows the mean and standard error of the per-capita values for **(A)** distance moved, **(B)** intake, **(C)** number of associations, or encounters, with other individuals. In a number of ecological parameter combinations, the evolutionary shift in movement strategies due to pathogen introduction causes reductions in intake (panel B) that are comparable to a halving of landscape productivity. Means and standard deviations are shown before (G = 3,000) and after (G = 3,500) pathogen introduction; each data point represents 10 replicates of the relevant parameter combination.](figures/fig_eco_compare_default.png)

\newpage
