---
editor_options:
  chunk_output_type: console
output:
  pdf_document: default
  html_document:
    df_print: paged
---

## Sporadic introduction of infectious pathogens

We implemented a variant of our main model, in which the infectious pathogen is introduced only sporadically after the first introduction event (at G = 3,000).
Specifically, we modelled probabilistic introduction of the pathogen in each generation following the initial introduction.
We call the per-generation probability of a novel pathogen introduction event the 'spillover rate'.
We ran 10 replicates each of this model variant and examined whether there was a similar evolutionary shift in social movement strategies as seen in our default implementation.
Since it is the main parameter of interest, we ran this model variant for three values of the spillover rate: 0.05, 0.1, and 0.25.
We kept all other model parameters similar to the default scenario of our main model: a landscape productivity $R$ of 2, and a per-timestep infection cost $\delta E$ of 0.25.
Cross-species novel pathogen introductions are likely to become more common with climate change, and so we chose these spillover rate values to represent different scenarios under altered global regimes of pathogen transfer.
Our model's default implementation may be seen as an extreme case of the models considered here, with a spillover rate of 1.0.

### Evolutionary outcomes of the percentage cost implementation

The social movement strategies evolved prior to pathogen introduction are identical to those seen in our default implementation.
This is because the percentage cost implementation differs from the default only after the pathogen is introduced.

After pathogen introduction, there is a rapid evolutionary shift in movement strategies.
This shift is similar to that in our default implementation, but the strategies evolved are different.
Rather than the agent avoiding strategy of the default implementation, it is the handler tracking strategy that is most common across parameter combinations.
When the costs of infection are low, the agent tracking strategy persists; when the resource landscape's productivity can offset the cost of infection, agent tracking is the commonest strategy.

![**Rapid evolutionary change, but different evolutionary outcomes, in an alternative implementation of disease costs.** In our alternative, percentage costs implementation of the infectious pathogen, there is a rapid shift in the mix of movement strategies after pathogen introduction. The handler tracking strategy becomes common across most parameter combinations, except when social information is not very useful (high productivity $R \geq$ 2), and the cost of disease is relatively low ($\delta E$ = 2.5%). ](figures/fig_evo_change_percent_cost.png){ width=70% }

### Ecological consequences in the percentage cost implementation

Surprisingly, the implementation of a different cost structure for the novel, infectious pathogen does not affect ecological, population level outcomes when compared with outcomes in our default implementation of direct costs.
Across parameter combinations where there is a rapid evolutionary transition from agent tracking to handler tracking as the dominant strategy, there is also an increase in distance moved, a reduction in intake, and a reduction in associations.

![**Rapid ecological changes accompany evolutionary shifts in an alternative implementation of disease costs, and are similar to the default implementation.** In the alternative percentage-costs implementation of the infectious pathogen, the outcomes are very similar to those in our default implementation of direct costs. Across most paramter combinations, there is an increase in movement, a reduction in intake, and a reduction in associations with other foragers. Each subplot in each panel shows the mean and standard error of the per-capita values for **(A)** distance moved, **(B)** intake, **(C)** number of associations, or encounters, with other individuals. Means and standard deviations are shown before (G = 3,000) and after (G = 3,500) pathogen introduction; each data point represents 10 replicates of the relevant parameter combination.](figures/fig_eco_compare_percent.png)

![**Social networks emerging from the implementation of the percentage infection costs scenario.** The social network in generation 3,000, when the pathogen is introduced, is very similar to pre-pathogen networks in the default implementation, with substantial social and spatial clustering. After novel pathogen introduction (G = 3,500), spatial-social networks are more dispersed, but not as much as the default direct costs implementation. Many more individuals are infected than in the default implementation. The figure shows networks from a single replicate where $\delta E$ = 5%, and $R$ = 2.](figures/fig_networks_percent.png){ width=70% }

\newpage
