---
editor_options: 
  chunk_output_type: console
---

# Run SIR models

Load libraries.

```{r}
library(data.table)
library(igraph)
library(tidygraph)
library(glue)
```

## Prepare parameters

```{r}
# disease parameters
beta = c(1, 5, 10)
gamma = c(0, 1)
threshold = c(1, 5, 10)

# make combinations
params_sir = CJ(beta, gamma, threshold)

beta = params_sir$beta
gamma = params_sir$gamma
threshold = params_sir$threshold
```

## Load networks from default scenario

Read parameter files to subset for default parameter combination, based on the "ofi" column.

```{r}
data_files = list.files(
  "data/results/networks",
  full.names = TRUE,
  pattern = "Rds"
)
```

## Run SIR models

```{r}
sc_repl = seq(10) # the number of replicates

data_sir_models = Map(
  data_files, sc_repl,
  f = function(file, sc_repl) {
    
    # load networks
    ntwk = readRDS(file)
    
    # pre disease
    d_pre = Map(
      beta, gamma, threshold,
      f = function(b, g, thr) {
        
        nt = ntwk[["3000"]] # hardcoded for now
        
        nt_ = as_tibble(nt)
        cost = unique(nt_$cost)
        regen = unique(nt_$regen_time)
        dispersal = unique(nt_$dispersal)
        scenario = unique(nt_$scenario)
        spillover_rate = unique(nt_$spillover_rate)
        
        # filter for threshold
        nt = nt %>% 
          activate(edges) %>% 
          filter(weight > thr) %>% 
          activate(nodes)
        
        d_pre_ = igraph::sir(
          graph = nt, beta = b, gamma = g, no.sim = 25
        ) |>
          pathomove::handle_sir_data(digits = 1)
        d_pre_$type = "pre"
        
        # add parameters
        d_pre_$beta = b
        d_pre_$gamma = g
        d_pre_$threshold = thr
        d_pre_$cost = cost
        d_pre_$regen = regen
        d_pre_$dispersal = dispersal
        d_pre_$scenario = scenario
        d_pre_$spillover_rate = spillover_rate
        
        d_pre_
      }
    ) |>
      rbindlist()
    
    # post disease
    d_post = Map(
      beta, gamma, threshold,
      f = function(b, g, thr) {
        
        nt = ntwk[["3500"]] # hardcoded for now
        
        nt_ = as_tibble(nt)
        cost = unique(nt_$cost)
        regen = unique(nt_$regen_time)
        dispersal = unique(nt_$dispersal)
        scenario = unique(nt_$scenario)
        spillover_rate = unique(nt_$spillover_rate)
        
        # filter for threshold
        nt = nt %>% 
          activate(edges) %>% 
          filter(weight > thr) %>% 
          activate(nodes)
        
        d_post_ = igraph::sir(
          graph = nt, beta = b, gamma = g, no.sim = 25
        ) |>
          pathomove::handle_sir_data(digits = 1)
        d_post_$type = "post"
        
        # add parameters
        d_post_$beta = b
        d_post_$gamma = g
        d_post_$threshold = thr
        d_post_$cost = cost
        d_post_$regen = regen
        d_post_$dispersal = dispersal
        d_post_$scenario = scenario
        d_post_$spillover_rate = spillover_rate
        
        d_post_
      }
    ) |>
      rbindlist()
    
    data = rbindlist(
      list(d_pre, d_post)
    )
    
    # add simulation replicate
    data$sc_repl = sc_repl
    data
    
  }
)

data_sir_models = rbindlist(data_sir_models)
```

```{r}
# sanity check
data_sir_models[class != "NS" & beta == 1 & 
                  gamma == 1 & threshold != 2 &
                  time < 5] %>% 
ggplot()+
  stat_summary(
    aes(time, mean, col = type)
  )+
  facet_grid(
    threshold ~ class,
    labeller = label_both
  )+
  # scale_x_sqrt()+
  coord_cartesian(
    xlim = c(0, 5)
  )
```

```{r}
# save data
fwrite(
  data_sir_models,
  file = "data/results/data_sir_models.csv"
)
```
