---
editor_options: 
  chunk_output_type: console
---

# Plot evolutionary consequences of spillover

```{r}
library(data.table)

library(ggplot2)
library(patchwork)
library(colorspace)

# custom functions
devtools::load_all()
```

Load data.

```{r}
# list files, read, and filter for default model options
files = list.files(
  "data/results/morph_data", 
  pattern = "csv",
  full.names = TRUE
)

data_all = lapply(files, fread)
data_all = rbindlist(data_all)

data = data_all[(local == 1)]
```

```{r}
# prepare to get proportions
popsize = 500
replicates = 10

# get average strategy proportions over replicates
data[, prop := N / popsize]

g_bin = 20
data[, gen_bin := (floor(gen / g_bin) * g_bin)]

# prepare to scale productivity
gen_time = 100
g_patho = 3000
genmax = 5000

# plot regen as rate per generation timesteps
data[, regen_r := gen_time / regen]

# remove highest percent cost
# data = data[!((cost == 0.1) & (infect_percent))]
```

```{r}
data = split(
  data,
  by = "infect_percent"
)
```

## Compare strategy evolution

```{r}
# rough draft
plots = lapply(
  data,
  function(df) {
    
    p = ggplot(df[
      social_strat != "non-handler tracking"
    ])+
      geom_point(
        aes(
          gen, prop,
          group = interaction(social_strat, repl),
          col = social_strat
        ),
        size = 0.1
      )+
      geom_vline(
        xintercept = g_patho,
        lty = 2,
        size = 0.3,
        col = "red"
        # col = c("grey", "black", "grey")
      )+
      scale_colour_discrete_sequential(
        palette = "Viridis", 
        rev = F,
        l1 = 30,
        # c1 = 20,
        name = NULL,
        limits = c("agent avoiding", "agent tracking", "handler tracking"),
        labels = stringr::str_to_sentence,
        na.value = "lightgrey"
      )+
      scale_x_continuous(
        # trans = ggallin::pseudolog10_trans,
        breaks = g_patho,
        labels = "Pathogen introduction",
        name = "Increasing productivity (social information less useful) \u279c",
        sec.axis = dup_axis(
          breaks = c(1, genmax / 2, genmax),
          labels = scales::comma_format(
            accuracy = 1
            # scale = 1/1000, suffix = "K"
          ),
          name = "Generations"
        )
      )+
      scale_y_continuous(
        labels = scales::percent,
        breaks = NULL,
        name = glue::glue("Increasing disease cost \u279c"),
        sec.axis = dup_axis(
          breaks = c(0, 0.5, 1),
          labels = scales::percent,
          name = "% Individuals"
        )
      )+
      facet_grid(
        cost ~ regen_r,
        as.table = F, 
        switch = c("both"),
        labeller = labeller(
          cost = function(x) sprintf("δE = %s", x),
          regen_r = function(x) sprintf("R = %s times/gen", x)
        )
      )+
      coord_cartesian(
        expand = T
      )+
      theme_test(
        base_size = 8, 
        base_family = "Arial"
      )+
      theme(
        legend.position = "top", 
        legend.key.height = unit(1, "mm"),
        strip.placement = "outside",
        strip.text = ggtext::element_markdown(),
        axis.text.x = element_text(hjust = 0.5, size = 6)
      )+
      guides(
        colour = guide_legend(
          override.aes = list(
            size = 2
          )
        )
      )
    
    p
  }
)
```

```{r}
library(patchwork)

figure_compare = wrap_plots(
  plots
)

figure_compare
```

```{r}
ggsave(
  plot = figure_compare,
  filename = "figures/fig_compare_cost_type.png",
  height = 100, width = 240, units = "mm"
)
```

## Compare movement, intake, and associations

```{r}
# list files, read, and filter for default model options
files = list.files(
  "data/results/gen_data", 
  pattern = "csv",
  full.names = TRUE
)

data_all = lapply(files, fread)
data_all = rbindlist(data_all)

data = data_all[(local == 1)]
data = data[!((cost == 0.1) & (infect_percent))]

# plot regen as rate per generation timesteps
data[, regen_r := gen_time / regen]
g_bin = 50
data[, gen_bin := floor(gen / g_bin) * g_bin]

# split by cost implementation
data = split(
  data,
  by = "infect_percent"
)
```

```{r}
plots_eco = lapply(
  data,
  function(df) {
    
    df = melt(
      df[, c("intake.mean", "moved.mean", "assoc.mean",
             "gen_bin", "cost", "regen_r", "repl")],
      id.vars = c("gen_bin", "cost", "regen_r", "repl")
    )
    
    df[, value := value / (max(value)), by = c("cost", "regen_r", "variable")]
    
    ggplot(df)+
      stat_summary(
        aes(
          gen_bin, value,
          group = interaction(variable, repl),
          col = variable
        ),
        geom = "point"
      )+
      geom_vline(
        xintercept = g_patho,
        lty = 2,
        size = 0.3,
        col = "red"
        # col = c("grey", "black", "grey")
      )+
      scale_colour_brewer(
        palette = "Accent",
        name = NULL
      )+
      scale_fill_brewer(
        palette = "Accent",
        name = NULL
      )+
      scale_x_continuous(
        # trans = ggallin::pseudolog10_trans,
        breaks = 500,
        labels = "Pathogen introduction",
        name = "Increasing productivity (social information less useful) \u279c",
        sec.axis = dup_axis(
          breaks = c(1, 500, 1000),
          labels = scales::comma_format(
            accuracy = 1
            # scale = 1/1000, suffix = "K"
          ),
          name = "Generations"
        )
      )+
      scale_y_continuous(
        labels = scales::percent,
        breaks = NULL,
        name = glue::glue("Increasing disease cost \u279c"),
        sec.axis = dup_axis(
          breaks = c(0, 0.5, 1),
          labels = scales::percent,
          name = "% of variable max."
        )
      )+
      facet_grid(
        cost ~ regen_r,
        as.table = F, 
        switch = c("both"),
        labeller = labeller(
          cost = function(x) sprintf("δE = %s", x),
          regen_r = function(x) sprintf("R = %s times/gen", x)
        )
      )+
      coord_cartesian(
        expand = T
      )+
      theme_test(
        base_size = 8, 
        base_family = "Arial"
      )+
      theme(
        legend.position = "top", 
        legend.key.height = unit(1, "mm"),
        strip.placement = "outside",
        strip.text = ggtext::element_markdown(),
        axis.text.x = element_text(hjust = 0.5, size = 6)
      )+
      guides(
        colour = guide_legend(
          override.aes = list(
            size = 2
          )
        )
      )
  }
)
```

```{r}
plots_eco = wrap_plots(
  plots_eco
)

plots_eco

ggsave(
  plot = plots_eco,
  filename = "figures/fig_compare_cost_type_eco.png",
  height = 100, width = 240, units = "mm"
)
```

