---
editor_options: 
  chunk_output_type: console
---

# Plot evolutionary consequences of spillover

```{r}
library(data.table)

library(ggplot2)
library(patchwork)
library(colorspace)
```

Load data.

```{r}
data = fread("data/results/data_si_morphs.csv")
data = data[social_strat != "non-handler tracking"]

# summarise
data[, gen_round := plyr::round_any(gen, 25)]
# handle for 5 replicates, and 5 obs over 25 gens
data_si_evo = data[, list(sum = sum(N) / (500 * 5 * 5)), 
                   by = c("social_strat", "cost", "regen", "gen_round")]

# levels of productivity
data_si_evo[, regen := factor(regen, levels = c("100", "50", "20"))]
```

```{r}
fig1 =
  ggplot(data_si_evo)+
  geom_area(
    aes(
      gen_round, sum, 
      fill = social_strat
    )
  )+
  geom_vline(
    xintercept = 3334,
    lty = 2,
    size = 0.3
    # col = c("grey", "black", "grey")
  )+
  scale_fill_discrete_sequential(
    palette = "Viridis", 
    rev = F,
    l1 = 30,
    name = NULL,
    labels = stringr::str_to_sentence
  )+
  scale_x_continuous(
    breaks = 3334,
    labels = "Spillover begins",
    name = "Increasing productivity \u279c",
    sec.axis = dup_axis(
      breaks = c(1000, 3000, 5000),
      labels = scales::comma_format(
        accuracy = 1
        # scale = 1/1000, suffix = "K"
      ),
      name = "Generations"
    )
  )+
  scale_y_continuous(
    labels = scales::percent,
    breaks = NULL,
    name = glue::glue("Increasing disease cost \u279c"),
    sec.axis = dup_axis(
      breaks = c(0.1, 0.5, 0.9),
      labels = scales::percent,
      name = "% Individuals"
    )
  )+
  facet_grid(
    cost ~ regen, 
    as.table = F, 
    switch = c("both"),
    labeller = labeller(
      cost = label_both,
      regen = label_both
    )
  )+
  coord_cartesian(
    expand = F,
    # ylim = c(0, 1),
    xlim = c(1, 5000)
  )+
  theme_test(
    base_size = 11,
    base_family = "Arial"
  )+
  theme(
    legend.position = "top", 
    legend.key.height = unit(1, "mm"),
    strip.placement = "outside",
    axis.text.x = element_text(hjust = 0.5, size = 8)
  )

ggsave(
  plot = fig1,
  filename = "figures/fig_1_new.png",
  height = 114, width = 114, units = "mm"
)
```


Load generation data.

```{r}
# load data
data = fread("data/results/data_gen.csv")
data = data[scenario == "spillover"]

# summarise etc
data[, gen_round := plyr::round_any(gen, 10)]
data[, energy.mean := fifelse(scenario == "spillover" & gen < 3334, NA_real_, energy.mean)]

# add col for representation
data[, gen_abs := gen - 3334]
```

## Intake and energy

```{r}
data = data[, c("gen_abs", "intake.mean", 
                       "energy.mean", "moved.mean", "assoc.mean")]
data = melt(
  data,
  id.vars = "gen_abs"
)
```


```{r}
plot_intake =
ggplot(data[variable %in% c("intake.mean", "energy.mean")])+
  geom_bin2d(
    data = data[variable == "intake.mean"],
    aes(
      gen_abs, value,
    ),
    binwidth = c(0.2, 0.25),
    show.legend = F,
    alpha = 0.8
  )+
  geom_hline(
    yintercept = 0,
    lty = 3
  )+
  geom_vline(
    data = data.table(
      x = 0, # 0.667 * 5000,
      scenario = 3
    ),
    aes(
      xintercept = x
    ),
    lty = 3
  )+
  stat_summary(
    fun = mean,
    fun.min = ci_lower,
    fun.max = ci_upper,
    aes(
      gen_abs, value,
      colour = variable,
    ),
    geom = "line",
    alpha = 0.8
  )+
  stat_summary(
    data = data[variable %in% c("intake.mean", "energy.mean") & 
           between(gen_abs, -25, 25)],
    fun = mean,
    fun.min = ci_lower,
    fun.max = ci_upper,
    aes(
      gen_abs, value,
      colour = variable,
      shape = variable
    ),
    fill = "grey99"
  )+
  scale_fill_continuous_sequential(
    palette = "Batlow",
    trans = "sqrt"
  )+
  scale_shape_manual(
    values = c(21, 24),
    breaks = c("energy.mean", "intake.mean"),
    labels = c("Net energy", "Intake")
  )+
  scale_colour_manual(
    values = c("indianred", "darkgreen"),
    breaks = c("energy.mean", "intake.mean"),
    labels = c("Net energy", "Intake")
  )+
  scale_x_continuous(
    trans = ggallin::pseudolog10_trans,
    breaks = c(-3000, -100, -5, 5, 100, 1500),
    labels = scales::comma_format(
      accuracy = 1
    ),
    name = "Gens. since spillover",
    sec.axis = sec_axis(
      trans = function(x) x + 3334,
      breaks = c(0, 3000, 3334, 5000),
      labels = scales::comma_format(
        accuracy = 1
      ),
      name = "Generations"
    )
  )+
  theme_test(base_family = "Arial")+
  theme(
    legend.position = c(0.2, 0.15),
    legend.key = element_blank(),
    legend.background = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(
      face = "italic"
    )
  )+
  labs(
    x = NULL,
    y = "Per-capita intake",
    colour = NULL,
    shape = NULL
  )
```

```{r}
ggsave(
  plot_intake,
  filename = "figures/fig_energy_intake.png",
  height = 3, width = 3
)
```

## Movement

```{r}
plot_movement =
ggplot(data[variable %in% c("moved.mean")])+
  geom_bin2d(
    aes(
      gen_abs, value,
    ),
    binwidth = c(0.2, 1),
    show.legend = F,
    alpha = 0.8
  )+
  geom_hline(
    yintercept = 0,
    lty = 3
  )+
  geom_vline(
    data = data.table(
      x = 0, # 0.667 * 5000,
      scenario = 3
    ),
    aes(
      xintercept = x
    ),
    lty = 3
  )+
  stat_summary(
    fun = mean,
    fun.min = ci_lower,
    fun.max = ci_upper,
    aes(
      gen_abs, value,
    ),
    colour = "navy",
    geom = "line",
    alpha = 0.8
  )+
  stat_summary(
    data = data[variable %in% c("moved.mean") & 
           between(gen_abs, -25, 25)],
    fun = mean,
    fun.min = ci_lower,
    fun.max = ci_upper,
    aes(
      gen_abs, value,
      shape = variable
    ),
    colour = "navy",
    fill = "grey99",
    shape = 21
  )+
  scale_fill_continuous_sequential(
    palette = "Purple-Yellow",
    trans = "sqrt"
  )+
  scale_x_continuous(
    trans = ggallin::pseudolog10_trans,
    breaks = c(-3000, -100, -5, 5, 100, 1500),
    labels = scales::comma_format(
      accuracy = 1
    ),
    name = "Gens. since spillover",
    sec.axis = sec_axis(
      trans = function(x) x + 3334,
      breaks = c(0, 3000, 3334, 5000),
      labels = scales::comma_format(
        accuracy = 1
      ),
      name = "Generations"
    )
  )+
  theme_test(base_family = "Arial")+
  theme(
    legend.position = c(0.2, 0.15),
    legend.key = element_blank(),
    legend.background = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(
      face = "italic"
    )
  )+
  coord_cartesian(
    ylim = c(75, 90)
  )+
  labs(
    x = NULL,
    y = "Distance moved",
    colour = NULL,
    shape = NULL
  )
```

```{r}
ggsave(
  plot_movement,
  filename = "figures/fig_movement.png",
  height = 3, width = 3
)
```

## Social information use

```{r}
# get morph data
data_si = fread("data/results/data_morphs.csv")
data_si = data_si[scenario == "spillover"]
data_si[, gen_round := plyr::round_any(gen, 400)]

# get social information strategies
data_si = data_si[, list(prop = .N / 500), 
               by = c("gen", "social_strat", "scenario", "repl", "gen_round")]
data_si[, scenario := fcase(
  scenario == "nopatho", 1,
  scenario == "endemic", 2,
  scenario == "spillover", 3
)]
```

```{r}
ggplot(data_si)+
  geom_line(
    aes(gen, prop, col = social_strat),
    position = "identity"
  )+
  facet_grid(
    rows = "repl"
  )
```


```{r}
# subset data
data_si = data_si[social_strat %in% c("handler tracking", "agent tracking")]
data_si[, gen_abs := gen - 3334]

data_si = data_si[, c("gen_abs", "prop", "social_strat")]
```

```{r}
plot_agent_avoid =
  ggplot(
    data_si
  )+
  geom_bin2d(
    data = data_si[social_strat %in% c("handler tracking")],
    aes(
      gen_abs, prop
    ),
    binwidth = c(0.2, 0.02),
    alpha = 0.8,
    show.legend = F
  )+
  stat_summary(
    fun = median,
    fun.min = ci_lower,
    fun.max = ci_upper,
    aes(
      gen_abs, prop,
      colour = social_strat,
    ),
    show.legend = T,
    geom = "line",
    position = position_identity()
  )+
  stat_summary(
    data = data_si[between(gen_abs, -25, 25)],
    fun = median,
    # fun.min = ci_lower,
    # fun.max = ci_upper,
    aes(
      gen_abs, prop,
      colour = social_strat,
      shape = social_strat,
    ),
    show.legend = T,
    fill = "grey99",
    # position = position_dodge(width = 200),
  )+
  scale_shape_manual(
    values = c(
      "agent tracking" = 21, 
      "handler tracking" = 24
      ),
    breaks = c("agent tracking", "handler tracking"),
    labels = c("All agents", "Successful foragers")
  )+
  scale_x_continuous(
    trans = ggallin::pseudolog10_trans,
    breaks = c(-3000, -100, -5, 5, 100, 1500),
    labels = scales::comma_format(
      accuracy = 1
    ),
    name = "Gens. since spillover",
    sec.axis = sec_axis(
      trans = function(x) x + 3334,
      breaks = c(0, 3000, 3334, 5000),
      labels = scales::comma_format(
        accuracy = 1
      ),
      name = "Generations"
    )
  )+
  theme_test(base_family = "Arial")+
  scale_y_continuous(
    labels = scales::percent
  )+
  scale_colour_manual(
    values = c(
      "agent tracking" = "steelblue", 
      "handler tracking" = "indianred"
    ),
    breaks = c("agent tracking", "handler tracking"),
    labels = c("All agents", "Successful foragers")
  )+
  scale_fill_continuous_sequential(
    palette = "Heat 2"
  )+
  geom_hline(
    yintercept = 0,
    lty = 3
  )+
  geom_vline(
    data = data.table(
      x = 0, # 0.667 * 5000,
      scenario = 3
    ),
    aes(
      xintercept = x
    ),
    lty = 3
  )+
  coord_cartesian(
    ylim = c(0, 1)
  )+
  theme_test(base_family = "Arial")+
  theme(
    strip.background = element_blank(),
    strip.text = element_text(
      face = "italic"
    ),
    axis.text.y = element_text(
      angle = 90, hjust = 0.5
    ),
    legend.background = element_blank(),
    legend.position = "top",
    legend.justification = "right"
  )+
  labs(
    y = "% Agents tracking",
    x = "Generation",
    shape = NULL,
    colour = NULL
  )
```

## Associations

```{r}
plot_assoc =
ggplot(data[variable %in% c("assoc.mean")])+
  geom_bin2d(
    aes(
      gen_abs, value,
    ),
    binwidth = c(0.2, 0.05),
    show.legend = F,
    alpha = 0.8
  )+
  geom_hline(
    yintercept = 0,
    lty = 3
  )+
  geom_vline(
    data = data.table(
      x = 0, # 0.667 * 5000,
      scenario = 3
    ),
    aes(
      xintercept = x
    ),
    lty = 3
  )+
  stat_summary(
    fun = mean,
    fun.min = ci_lower,
    fun.max = ci_upper,
    aes(
      gen_abs, value,
    ),
    colour = "grey20",
    geom = "line",
    alpha = 0.8
  )+
  stat_summary(
    data = data[variable %in% c("assoc.mean") & 
           between(gen_abs, -25, 25)],
    fun = mean,
    fun.min = ci_lower,
    fun.max = ci_upper,
    aes(
      gen_abs, value,
      shape = variable
    ),
    colour = "grey20",
    fill = "grey99",
    shape = 21
  )+
  scale_fill_continuous_sequential(
    palette = "Sunset"
  )+
  scale_x_continuous(
    trans = ggallin::pseudolog10_trans,
    breaks = c(-3000, -100, -5, 5, 100, 1500),
    labels = scales::comma_format(
      accuracy = 1
    ),
    name = "Gens. since spillover",
    sec.axis = sec_axis(
      trans = function(x) x + 3334,
      breaks = c(0, 3000, 3334, 5000),
      labels = scales::comma_format(
        accuracy = 1
      ),
      name = "Generations"
    )
  )+
  scale_y_continuous(
    trans = "log10",
    labels = scales::comma
  )+
  theme_test(base_family = "Arial")+
  theme(
    legend.position = c(0.2, 0.15),
    legend.key = element_blank(),
    legend.background = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(
      face = "italic"
    ),
    axis.text.y = element_text(
      angle = 90, hjust = 0.5
    )
  )+
  labs(
    x = NULL,
    y = "Encounters w/ individuals",
    colour = NULL,
    shape = NULL
  )
```

```{r}
ggsave(
  plot_assoc,
  filename = "figures/fig_assoc.png",
  height = 3, width = 3
)
```

## Make Figure 1

```{r}
fig_1 =
wrap_plots(
  plot_agent_avoid,
  plot_intake, 
  plot_movement,
  plot_assoc,
  ncol = 2
  # guides = "collect"
) &
  plot_annotation(
    tag_levels = c("A", 1)
  ) &
  theme(
    legend.position = "top",
    legend.key.height = unit(1, units = "mm"),
    plot.tag = element_text(
      face = "bold",
      size = 10
    )
  )

ggsave(
  fig_1,
  filename = "figures/fig_01.png",
  height = 174, width = 174, units = "mm"
)
```

