---
editor_options: 
  chunk_output_type: console
---

# Plot evolutionary consequences of spillover

```{r}
library(data.table)

library(ggplot2)
library(patchwork)
library(colorspace)

# custom functions
devtools::load_all()
```

Load data.

```{r}
# list files, read, and filter for default model options
files = list.files(
  "data/results/morph_data", 
  pattern = "csv",
  full.names = TRUE
)

data_all = lapply(files, fread)
data_all = rbindlist(data_all)

data = data_all[(local == 1) & (infect_percent == T)]
```


```{r}
data = data[social_strat != "non-handler tracking"]
data[, gen_round := plyr::round_any(gen, 10)]

# popsize
popsize = 500

# handle for 5 replicates, and 5 obs over 10 gens (observation twice per gen)
data_si_evo = data[, list(
  prop = sum(N) / (popsize * max(repl) * 5)
), by = c("social_strat", "cost", "regen", "gen_round")]

gen_time = 100

# plot regen as rate per generation timesteps
data_si_evo[, regen_r := gen_time / regen]

# levels of productivity
# data_si_evo[, regen := factor(regen, levels = c("100", "50", "20"))]
```

```{r}
ggplot(data)+
  geom_line(
    aes(
      gen, N,
      group = interaction(social_strat, repl),
      col = social_strat
    ),
    # geom = "line",
    size = 1
  )+
  scale_x_continuous(
    # trans = ggallin::pseudolog10_trans
  )+
  coord_cartesian(
    # xlim = c(-100, NA)
  )+
  facet_grid(
    cost ~ regen
  )

ggplot(data)+
  stat_summary(
    aes(
      gen_round, N,
      # group = interaction(social_strat, repl),
      col = social_strat
    ),
    # geom = "line",
    # size = 1
  )+
  scale_x_continuous(
    # trans = ggallin::pseudolog10_trans
  )+
  coord_cartesian(
    # xlim = c(-100, NA)
  )+
  facet_grid(
    cost ~ regen
  )
```


```{r}
# fig1 =
  ggplot(data_si_evo)+
  geom_area(
    aes(
      gen_round, prop, 
      fill = social_strat
    )
  )+
  geom_vline(
    xintercept = 3300,
    lty = 2,
    size = 0.3
    # col = c("grey", "black", "grey")
  )+
  scale_fill_discrete_sequential(
    palette = "Viridis", 
    rev = F,
    l1 = 30,
    name = NULL,
    limits = c("agent avoiding", "agent tracking", "handler tracking"),
    labels = stringr::str_to_sentence
  )+
  scale_x_continuous(
    breaks = 1200,
    labels = "Pathogen introduction",
    name = "Increasing productivity \u279c",
    sec.axis = dup_axis(
      # breaks = c(1000, 3000, 5000),
      labels = scales::comma_format(
        accuracy = 1
        # scale = 1/1000, suffix = "K"
      ),
      name = "Generations"
    )
  )+
  scale_y_continuous(
    labels = scales::percent,
    breaks = NULL,
    name = glue::glue("Increasing disease cost \u279c"),
    sec.axis = dup_axis(
      breaks = c(0.1, 0.5, 0.9),
      labels = scales::percent,
      name = "% Individuals"
    )
  )+
  facet_grid(
    cost ~ regen_r, 
    as.table = F, 
    switch = c("both"),
    labeller = labeller(
      cost = function(x) sprintf("δE = %s", x),
      regen_r = function(x) sprintf("R = %s times/gen", x)
    )
  )+
  coord_cartesian(
    expand = F,
    # ylim = c(0, 1),
    # xlim = c(1, 2000)
  )+
  theme_test(
    base_size = 11, 
    base_family = "Arial"
  )+
  theme(
    legend.position = "top", 
    legend.key.height = unit(1, "mm"),
    strip.placement = "outside",
    strip.text = ggtext::element_markdown(),
    axis.text.x = element_text(hjust = 0.5, size = 8)
  )

ggsave(
  plot = fig1,
  filename = "figures/fig_01.png",
  height = 114, width = 114, units = "mm"
)
```
