---
editor_options: 
  chunk_output_type: console
---

```{r}
library(data.table)

library(ggplot2)
library(patchwork)
library(colorspace)

# custom functions
devtools::load_all()
```

## Focal strategy data

Load generation strategy data.

```{r}
files = list.files(
  "data/results/morph_data", 
  pattern = "csv",
  full.names = TRUE
)

data_all = lapply(files, fread)
data_all = rbindlist(data_all)

df_strat = data_all[(local == 1) & (infect_percent == F)]
df_strat = df_strat[(cost == 0.25) & (regen == 50)]

# popsize
popsize = 500
df_strat[, prop := N / popsize]
g_bin = 100
df_strat[, gen_bin := (floor(gen / g_bin) * g_bin)]

# get time since pathogen
sgen = 3000
genmax = 5000
df_strat[, gen_abs := gen_bin - sgen]

# focus on generations before and after spillover
df_strat[, gen_abs := fifelse(
  abs(gen - sgen) < g_bin, gen - sgen, gen_abs
)]
```

## Plot evolutionary change in default scenario

```{r}
fig_1a =
ggplot(df_strat[
  social_strat != "non-handler tracking"
])+
  stat_summary(
    aes(
      gen_abs, prop, 
      colour = social_strat,
    ),
    geom = "line"
  )+
  stat_summary(
    aes(
      gen_abs, prop, 
      col = social_strat,
    ),
    shape = 1,
    size = 0.3
  )+
  geom_vline(
    xintercept = c(0, 25),
    lty = 2,
    size = 0.3,
    col = c("red", "grey")
  )+
  scale_colour_discrete_sequential(
    palette = "Viridis",
    l2 = 80,
    rev = F,
    name = NULL,
    limits = c("agent avoiding", "agent tracking", "handler tracking"),
    labels = stringr::str_to_sentence,
    na.value = "lightgrey"
  )+
  scale_x_continuous(
    trans = ggallin::pseudolog10_trans,
    breaks = c(-250, -25, 0, 25, 250),
    labels = scales::comma_format(
      accuracy = 1
    ),
    name = "Gens. after pathogen intro.",
    sec.axis = sec_axis(
      trans = function(x) x + sgen,
      breaks = c(1, sgen, genmax),
      labels = scales::comma_format(
        accuracy = 1
      ),
      name = "Generations"
    )
  )+
  scale_y_continuous(
    breaks = c(0, 0.5, 1),
    labels = scales::percent,
    name = "% Individuals"
  )+
  coord_cartesian()+
  theme_test(
    base_family = "Arial",
    base_size = 10
  )+
  theme(
    legend.position = "top", 
    legend.key.height = unit(1, "mm"),
    legend.key.width = unit(2, "mm"),
    axis.text.x = element_text(hjust = 0.5),
    axis.text.y = element_text(
      angle = 90, hjust = 0.5  
    )
  )
```

## Data social information importance

```{r}
files = list.files(
  "data/results/si_imp_data", 
  pattern = "csv",
  full.names = TRUE
)

data_all = lapply(files, fread)
data_all = rbindlist(data_all)

df_si = data_all[(local == 1) & (infect_percent == F)]
df_si = df_si[(cost == 0.25) & (regen == 50)]

# popsize
popsize = 500

df_si[, prop := N / popsize]
g_bin = 100
df_si[, gen_bin := (floor(gen / g_bin) * g_bin)]

# get time since pathogen
sgen = 3000
genmax = 5000
df_si[, gen_abs := gen_bin - sgen]

# focus on generations before and after spillover
df_si[, gen_abs := fifelse(
  abs(gen - sgen) < g_bin, gen - sgen, gen_abs
)]
```

```{r}
# get weighted mean and variance in social info importance
df_si_mean = df_si[, list(
  mean = weighted.mean(si_imp, w = N),
  sd = Hmisc::wtd.var(si_imp, weights = N)
), by = "gen"]

df_si_mean[, c("y", "ymin", "ymax") := list(
  mean,
  mean - sd,
  mean + sd
)]
```

### Figure social information importance

```{r}
fig_1b = 
  ggplot()+
  geom_tile(
    data = df_si[repl == 10],
    aes(
      gen, si_imp,
      fill = N / popsize
    )
  )+
  geom_pointrange(
    data = df_si_mean[
      gen %% 100 == 0
    ],
    aes(
      gen, y,
      ymin = ymin,
      ymax = ymax
    ),
    shape = 1,
    size = 0.2,
    col = alpha("darkslateblue", 1),
  )+
  geom_hline(
    yintercept = 0.5,
    col = "grey",
    lty = 2,
    size = 0.2
  )+
  geom_vline(
    xintercept = c(sgen),
    lty = 2,
    size = 0.3,
    col = c("red")
  )+
  scale_fill_gradientn(
    colours = c(
      "grey95", 
      viridis::magma(
        5,
        direction = -1
      )
    ),
    values = scales::rescale(
      c(
        1, 10, 50, 100, 200, 500
      ) / popsize
    ),
    limits = c(1, 500) / popsize,
    breaks = c(1, 250, 500) / popsize,
    labels = scales::percent,
    name = "% Indiv."
  )+
  scale_x_continuous(
    breaks = c(2500, 3000, 4000, 5000),
    labels = scales::comma_format(
      accuracy = 1
    ),
    name = "Generations",
    sec.axis = dup_axis(
      breaks = sgen,
      labels = "Pathogen introduction",
      name = NULL
    )
  )+
  scale_y_continuous(
    labels = scales::percent,
    name = "% Importance of\nsocial information"
  )+
  coord_cartesian(
    xlim = c(2500, NA),
    ylim = c(0, 0.75)
  )+
  theme_test(
    base_family = "Arial",
    base_size = 10
  )+
  theme(
    legend.position = "top", 
    legend.key.height = unit(1, "mm"),
    legend.key.width = unit(2.5, "mm"),
    legend.title = element_text(
      vjust = 1.5
    ),
    # axis.text.x = element_text(hjust = 0.5, size = 6),
    axis.text.y = element_text(
      angle = 90, hjust = 0.5  
    )
  )
```

### Intermediate figure SI change

```{r}
fig_1_intermediate = wrap_plots(
  fig_1a, fig_1b,
  guides = "collect"
) &
  plot_annotation(
    tag_levels = "A"
  ) &
  theme(
    plot.tag = element_text(
      face = "bold"
    ),
    legend.position = "bottom",
    legend.justification = "left",
    legend.text = element_text(
      size = 8
    ),
    legend.title = element_text(
      size = 8
    )
  )

# save intermediate figure
ggsave(
  plot = fig_1_intermediate,
  filename = "figures/fig_1_intermediate.png",
  width = 120,
  height = 75,
  units = "mm"
)
```


## Data ecological outcomes

Load generation data.

```{r}
# list files, read, and filter for default model options
files = list.files(
  "data/results/gen_data", 
  pattern = "csv",
  full.names = TRUE
)

data_all = lapply(files, fread)
data_all = rbindlist(data_all)

df_eco = data_all[(local == 1) & (infect_percent == F)]
df_eco = df_eco[(cost == 0.25) & (regen == 50)]

# popsize
popsize = 500
g_bin = 100
df_eco[, gen_bin := (floor(gen / g_bin) * g_bin)]

# get time since pathogen
sgen = 3000
genmax = 5000
df_eco[, gen_abs := gen_bin - sgen]

# focus on generations before and after spillover
df_eco[, gen_abs := fifelse(
  abs(gen - sgen) < g_bin, gen - sgen, gen_abs
)]
```

### Intake

```{r}
df_eco = df_eco[, c("gen_abs", "intake.mean", 
                    "moved.mean", "assoc.mean")]
df_eco = melt(
  df_eco,
  id.vars = "gen_abs"
)

## colours for background
cols = RColorBrewer::brewer.pal(3, "Dark2")

# split by variable
```

```{r}
ggplot(df_eco)+
  stat_summary(
    aes(
      gen_abs, value, 
      colour = variable,
    ),
    geom = "line"
  )+
  stat_summary(
    aes(
      gen_abs, value,
      colour = variable
    ),
    size =
  )+
  geom_vline(
    xintercept = c(0, 25),
    lty = 2,
    size = 0.3,
    col = rep(c("red", "grey"), 3)
  )+
  facet_wrap(
    ~variable, scales = "free_y"
  )+
  scale_colour_discrete_qualitative(
    palette = "Harmonic"
  )+
  scale_x_continuous(
    trans = ggallin::pseudolog10_trans,
    breaks = c(-250, -25, 25, 250),
    labels = scales::comma_format(
      accuracy = 1
    ),
    name = "Gens. since spillover",
    sec.axis = sec_axis(
      trans = function(x) x + sgen,
      breaks = c(1, sgen, genmax),
      labels = scales::comma_format(
        accuracy = 1
      ),
      name = "Generations"
    )
  )+
  theme_test(
    base_family = "Arial",
    base_size = 8
  )
```


```{r}
plot_intake =
ggplot(data[variable %in% c("intake.mean")])+
  stat_summary(
    # fun = mean,
    # fun.min = ci_lower,
    # fun.max = ci_upper,
    aes(
      gen_abs, value
    ),
    geom = "ribbon",
    size = 0.2,
    # colour = "grey",
    fill = alpha(cols[1], 0.3),
    show.legend = F
  )+
  stat_summary(
    fun = mean,
    # fun.min = ci_lower,
    # fun.max = ci_upper,
    aes(
      gen_abs, value,
    ),
    colour = "grey30",
    geom = "line",
    show.legend = F
  )+
  geom_vline(
    xintercept = c(0, 25),
    lty = 2,
    size = 0.3,
    col = "red"
  )+
  scale_x_continuous(
    trans = ggallin::ssqrt_trans,
    breaks = c(-sgen, -25, 25, sgen),
    labels = scales::comma_format(
      accuracy = 1
    ),
    name = "Gens. since spillover",
    sec.axis = sec_axis(
      trans = function(x) x + sgen,
      breaks = c(1, sgen, 1000),
      labels = scales::comma_format(
        accuracy = 1
      ),
      name = "Generations"
    )
  )+
  theme_test(
    base_family = "Arial",
    base_size = 8
  )+
  theme(
    # legend.position = c(0.2, 0.15),
    legend.key = element_blank(),
    legend.background = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(
      face = "italic"
    ),
    strip.placement = "outside"
  )+
  labs(
    x = NULL,
    y = "Per-capita intake",
    colour = NULL,
    shape = NULL
  )
```

```{r}
ggsave(
  plot_intake,
  filename = "figures/fig_energy_intake.png",
  height = 3, width = 3
)
```

## Movement

```{r}
plot_movement =
ggplot(data[variable %in% c("moved.mean")])+
  stat_summary(
    aes(
      gen_abs, value
    ),
    geom = "ribbon",
    size = 0.2,
    # colour = "grey",
    fill = alpha(cols[3], 0.3),
    show.legend = F
  )+
  stat_summary(
    fun = mean,
    # fun.min = ci_lower,
    # fun.max = ci_upper,
    aes(
      gen_abs, value
    ),
    colour = "grey30",
    geom = "line",
    show.legend = F
  )+
  geom_vline(
    data = data.table(
      x = 0, # 0.667 * 5000,
      scenario = 3
    ),
    aes(
      xintercept = x
    ),
    lty = 3
  )+
  scale_x_continuous(
    trans = ggallin::ssqrt_trans,
    breaks = c(-sgen, -25, -5, 5, 25, sgen),
    labels = scales::comma_format(
      accuracy = 1
    ),
    name = "Gens. since spillover",
    sec.axis = sec_axis(
      trans = function(x) x + sgen,
      breaks = c(1, 500, 1000),
      labels = scales::comma_format(
        accuracy = 1
      ),
      name = "Generations"
    )
  )+
  theme_test(
    base_family = "Arial",
    base_size = 8
  )+
  theme(
    # legend.position = c(0.2, 0.15),
    legend.key = element_blank(),
    legend.background = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(
      face = "italic"
    ),
    strip.placement = "outside"
  )+
  labs(
    x = NULL,
    y = "Distance moved",
    colour = NULL,
    shape = NULL
  )
```

```{r}
ggsave(
  plot_movement,
  filename = "figures/fig_movement.png",
  height = 3, width = 3
)
```

## Associations

```{r}
plot_assoc =
ggplot(data[variable %in% c("assoc.mean")])+
  stat_summary(
    aes(
      gen_abs, value
    ),
    geom = "ribbon",
    size = 0.2,
    fill = alpha(cols[2], 0.3),
    show.legend = F
  )+
  stat_summary(
    fun = mean,
    # fun.min = ci_lower,
    # fun.max = ci_upper,
    aes(
      gen_abs, value,
    ),
    colour = "grey30",
    geom = "line",
    show.legend = F
  )+
  geom_vline(
    data = data.table(
      x = 0, # 0.667 * 5000,
      scenario = 3
    ),
    aes(
      xintercept = x
    ),
    lty = 3
  )+
  scale_x_continuous(
    trans = ggallin::ssqrt_trans,
    breaks = c(-sgen, -25, -5, 5, 25, sgen),
    labels = scales::comma_format(
      accuracy = 1
    ),
    name = "Gens. since spillover",
    sec.axis = sec_axis(
      trans = function(x) x + sgen,
      breaks = c(1, 250, 500),
      labels = scales::comma_format(
        accuracy = 1
      ),
      name = "Generations"
    )
  )+
  scale_y_continuous(
    trans = "log10",
    labels = scales::comma
  )+
  theme_test(
    base_family = "Arial",
    base_size = 8
  )+
  theme(
    # legend.position = c(0.2, 0.15),
    legend.key = element_blank(),
    legend.background = element_blank(),
    strip.background = element_blank(),
    strip.text = element_text(
      face = "italic"
    ),
    axis.text.y = element_text(
      angle = 90, hjust = 0.5
    ),
    strip.placement = "outside"
  )+
  labs(
    x = NULL,
    y = "Associations",
    colour = NULL,
    shape = NULL
  )
```

```{r}
ggsave(
  plot_assoc,
  filename = "figures/fig_assoc.png",
  height = 3, width = 3
)
```

## Make Figure 1

```{r}
fig_1 =
wrap_plots(
  # plot_agent_avoid,
  fig_1a,
  plot_movement,
  plot_intake, 
  plot_assoc,
  ncol = 2,
  guides = "collect"
) &
  plot_annotation(
    tag_levels = c("A", 1)
  ) &
  theme(
    legend.position = "top",
    legend.justification = 0,
    legend.key.height = unit(1, units = "mm"),
    plot.tag = element_text(
      face = "bold",
      size = 10
    ),
    axis.text.x = element_text(
      size = 7
    )
  )

ggsave(
  fig_1,
  filename = "figures/fig_01.png",
  height = 120, width = 120, units = "mm"
)
```
