---
editor_options: 
  chunk_output_type: console
---

# Plot networks and SIR models

```{r}
library(data.table)
devtools::load_all()

library(ggplot2)

library(patchwork)
library(colorspace)
```

## Plot default scenario

```{r}
# spillover data and rounding
popsize = 500
replicates = 10
data_sir_models = fread("data/results/data_sir_models.csv")

# data_sir_models$mean = data_sir_models$mean / 500
data_sir_models = data_sir_models[class == "NR" & gamma == 1 &
                                    beta == 5 & threshold %in% c(1, 10) ]

# select scenario
data_default = data_sir_models[regen == 50 & cost == 0.25]

# round time, with larger bins later in time
# ie, increments of 0, 0.25, 0.5, 1, 2, 5, 10 etc.
data_default[, tround := plyr::round_any(time, 0.25)]
data_default[, tround := fifelse(
  time > 5, plyr::round_any(time, 0.5),
  tround
)]
data_default[, type := factor(type, levels = c("pre", "post"))]

# save data default sir
fwrite(
  data_default,
  file = "data/results/data_default_sir.csv"
)
```

```{r}
# load saved data to save time
data_default = fread("data/results/data_default_sir.csv")
data_default[, type := factor(type, levels = c("pre", "post"))]
# data_default = split(data_default, by = "threshold")
```


```{r}
# plot the progress of disease in default network sir models
plot_default =
  ggplot(data_default)+
    geom_hline(
      yintercept = 0.5,
      col = "grey",
      size = 0.2
    )+
    geom_bin2d(
      aes(
        time, mean / popsize,
        fill = type,
        alpha = ..density..
      ),
      show.legend = F
    )+
    stat_summary(
      aes(
        tround, mean / popsize, 
        colour = type,
        shape = type,
        group = interaction(type, threshold, beta)
      ),
      stroke = 0.8,
      size = 0.3,
      position = position_dodge(width = 0.1),
      show.legend = F
    )+
    facet_wrap(
      ~threshold,
      labeller = labeller(
        threshold = c(
          "1" = "1 encounter",
          "10" = "10 encounters"
        )
      )
    )+
    scale_colour_discrete_diverging(
      l2 = 50,# l2 = 40,
      palette = "Blue-Red 2",
      rev = FALSE,
      # palette = "Plasma",
      breaks = c("pre", "post"),
      labels = c("Pre-pathogen intro.", "Post-pathogen intro.")
    )+
    scale_fill_discrete_diverging(
      palette = "Blue-Red 2",
      rev = FALSE,
      # palette = "Plasma",
      breaks = c("pre", "post"),
      labels = c("Pre-pathogen intro.", "Post-pathogen intro.")
    )+
    scale_shape_manual(
      values = c(
        "pre" = 16,
        "post" = 17
      ),
      breaks = c("pre", "post"),
      labels = c("Pre-pathogen intro.", "Post-pathogen intro.")
    )+
    scale_y_continuous(
      labels = scales::percent,
      # breaks = c(0.01, 0.33, 0.67, 1)
    )+
    # scale_x_sqrt()+
    theme_test(
      base_size = 8
    )+
    theme(
      legend.position = "top",
      strip.background = element_blank(),
      strip.text = element_text(
        face = "bold"
      ),
      # strip.placement = "outside",
      axis.text.y = element_text(
        angle = 90,
        hjust = 0.5,
        size = 6
      )
    )+
    coord_cartesian(
      xlim = c(0, 10),
      ylim = c(0, 1)
    )+
    labs(
      x = "SIR model time",
      y = "% Agents infected",
      fill = NULL,
      colour = NULL,
      shape = NULL
    )
```

## Infections per generation

```{r}
# load data
data_infections_gen = fread("data/results/data_infections_gen.csv")
data_infections_gen[, gen_bin := round(gen, digits = -2)]
```

```{r}
sgen = 3000
genmax = 5000
popsize = 500

# make figures
fig_gen_infect =
ggplot(
  data_infections_gen[cost == 0.25 & regen == 50 
                      & dispersal == 2]
  )+
  geom_vline(
    xintercept = c(0, 25),
    lty = 2, 
    col = c("red", "grey")
  )+
  geom_point(
    aes(
      gen - sgen, n_infected / popsize
    ),
    shape = 4,
    show.legend = FALSE,
    colour = "steelblue",
    size = 0.1
  )+
  scale_x_continuous(
    trans = ggallin::ssqrt_trans,
    labels = scales::comma,
    breaks = c(-100, 0, 25, 500),
    name = "Gens. after pathogen intro."
  )+
  scale_y_continuous(
    labels = scales::percent,
    name = "% Population infected"
  )+
  coord_cartesian(
    expand = T,
    xlim = c(sgen - 100, genmax) - sgen,
    ylim = c(0, popsize) / popsize
  )+
  theme_test(
    base_size = 8
  )+
  theme(
    axis.text.y = element_text(
      angle = 90,
      hjust = 0.5,
      size = 6
    )
  )
```


Wrap all figures and save as figure 3.

```{r}
# wrap figures
fig_4 =
  wrap_plots(
  fig_gen_infect,
  plot_default,
  design = "ABB"
) &
  plot_annotation(
    tag_levels = c("A")
  ) &
  theme(
    plot.tag = element_text(
      face = "bold"
    ),
    legend.position = "bottom"
  )
```


```{r}
ggsave(
  fig_4,
  filename = "figures/fig_04.png",
  height = 60,
  width = 120,
  units = "mm"
)
```

## Plots for other scenarios

```{r}
# data_sir_models$mean = data_sir_models$mean / 500
data_all = copy(data_sir_models)

data_all[, tround := plyr::round_any(time, 0.25)]
data_all[, tround := fifelse(
  time > 5, plyr::round_any(time, 0.5),
  tround
)]

tmax = 100
# add regeneration rate
data_all[, regen_r := tmax / regen]

# select single SIR model paramter combination
data_all = data_all[gamma == 1 & beta == 5 & threshold %in% c(1, 10), ]

# assign type
data_all[, type := factor(type, levels = c("pre", "post"))]

# handle main types of simulation: default, percent, and global
data_all[, sim_type := fcase(
  cost < 0.1, "percent",
  cost >= 0.1 & dispersal == 10, "global",
  dispersal == 2, "default"
)]

# split data by disease type
data_all = split(data_all, by = c("sim_type"))
```

```{r}
# plot the progress of disease in all network sir models
plot_sir_all =
lapply(data_all, function(df) {
  ggplot(df)+
    geom_hline(
      yintercept = 0.5,
      col = "grey",
      lty = 1,
      size = 0.2
    )+
    annotate(
      geom = "rect",
      xmin = 7.5, xmax = 11,
      ymin = -1, ymax = 1.1,
      fill = "grey90",
      lty = 1,
      size = 0.2
    )+
    stat_summary(
      aes(
        tround, mean / popsize, 
        colour = type,
        lty = as.factor(threshold),
        group = interaction(type, threshold)
      ),
      # stroke = 0.8,
      size = 0.5,
      position = position_dodge(width = 0.1),
      geom = "line"
    )+
    facet_grid(
      cost ~ regen_r,
      as.table = F, 
      switch = c("both"),
      labeller = labeller(
        cost = function(x) {
          if(x >= 0.1) {
            sprintf("δE = %s", x)
          } else {
            scales::percent(as.numeric(x), prefix = "δE = ")
          }
        },
        regen_r = function(x) sprintf("R = %s times/gen", x)
      )
    )+
    scale_colour_discrete_diverging(
      l2 = 50,# l2 = 40,
      palette = "Blue-Red 2",
      rev = FALSE,
      # palette = "Plasma",
      breaks = c("pre", "post"),
      labels = c("Pre-pathogen intro.", "Post-pathogen intro.")
    )+
    scale_linetype(
      breaks = c("1", "10"),
      labels = c("1 encounter", 
                 "10 encounters"),
      name = NULL
    )+
    scale_y_continuous(
      labels = scales::percent,
      # breaks = c(0.01, 0.33, 0.67, 1)
    )+
    scale_x_continuous(
      breaks = NULL,
      sec.axis = dup_axis(
        breaks = seq(0, 10, 2.5),
        name = "SIR model simulation time"
      )
    )+
    theme_test(
      base_size = 8
    )+
    theme(
      legend.justification = "left",
      legend.position = "top",
      # strip.background = element_blank(),
      strip.text = element_text(
        face = "italic"
      ),
      strip.placement = "outside",
      axis.text.y = element_text(
        angle = 90,
        hjust = 0.5,
        size = 6
      )
    )+
    coord_cartesian(
      xlim = c(0, 10),
      ylim = c(0, 1)
    )+
    labs(
      x = "Increasing productivity (social information less useful) \u279c",
      y = "Cumulative infections (% indivs.)",
      fill = NULL,
      colour = NULL,
      shape = NULL
    )
})

# save to supplementary figures
Map(
  plot_sir_all,
  names(plot_sir_all),
  f = function(p, n) {
    ggsave(
      p,
      filename = glue("supplement/figures/fig_sir_compare_{n}.png"),
      height = 120, width = 120,
      units = "mm"
    )
  }
)
  
```
