---
editor_options: 
  chunk_output_type: console
---

# Plot evolutionary consequences of spillover

```{r}
library(data.table)
library(glue)

library(ggplot2)
library(patchwork)
library(colorspace)

# custom functions
devtools::load_all()
```

Load data.

```{r}
files = list.files(
  "data/results/morph_data", 
  pattern = "csv",
  full.names = TRUE
)

data_all = lapply(files, fread)
df_strat = rbindlist(data_all)

# popsize
popsize = 500
replicates = 10
df_strat[, prop := N / popsize]
g_bin = 100
df_strat[, gen_bin := (floor(gen / g_bin) * g_bin)]

# get time since pathogen
sgen = 3000
genmax = 5000
df_strat[, gen_abs := gen_bin - sgen]

df_strat = df_strat[gen %% 100 == 0,]

df_strat = df_strat[, list(
  prop = sum(prop) / (replicates)
), by = c(
  "gen", "social_strat", 
  "cost", "regen", "infect_percent", "dispersal"
)]

# regeneration rate
gen_time = 100
df_strat[, regen_r := gen_time / regen]
```

```{r}
# handle main types of simulation: default, percent, and global
df_strat[, sim_type := fcase(
  infect_percent == T, "percent",
  dispersal == 10, "global",
  dispersal == 2, "default"
)]
```

```{r}
df_strat = split(
  df_strat,
  by = "sim_type"
)
```

## Compare strategy evolution

```{r}
# rough draft
plots_evo = lapply(
  df_strat,
  function(df) {
    
    p = ggplot(df)+
      geom_col(
        aes(
          gen, prop,
          fill = social_strat
        ),
        width = 100,
        position = "stack"
      )+
      geom_vline(
        xintercept = sgen,
        lty = 2,
        size = 0.3,
        col = "red"
      )+
      scale_fill_discrete_sequential(
        palette = "Viridis",
        l2 = 80,
        rev = F,
        name = NULL,
        limits = c("agent avoiding", "agent tracking", "handler tracking"),
        labels = stringr::str_to_sentence,
        na.value = "lightgrey"
      )+
      scale_x_continuous(
        breaks = sgen,
        labels = "Pathogen introduction",
        name = "Increasing productivity (social information less useful) \u279c",
        sec.axis = dup_axis(
          breaks = c(1000, sgen, genmax),
          labels = scales::comma,
          name = "Generations"
        )
      )+
      scale_y_continuous(
        labels = scales::percent,
        breaks = NULL,
        name = glue::glue("Increasing disease cost \u279c"),
        sec.axis = dup_axis(
          breaks = c(0, 0.5, 1),
          labels = scales::percent,
          name = "% Individuals"
        )
      )+
      facet_grid(
        cost ~ regen_r,
        as.table = F, 
        switch = c("both"),
        labeller = labeller(
          cost = function(x) {
            if(x >= 0.1) {
              sprintf("δE = %s", x)
            } else {
              scales::percent(as.numeric(x), prefix = "δE = ")
            }
          },
          regen_r = function(x) sprintf("R = %s times/gen", x)
        )
      )+
      coord_cartesian(
        expand = F
      )+
      theme_test(
        base_size = 8, 
        base_family = "Arial"
      )+
      theme(
        legend.position = "top", 
        legend.key.height = unit(1, "mm"),
        strip.placement = "outside",
        strip.text = ggtext::element_markdown(),
        axis.text.x = element_text(hjust = 0.5, size = 6)
      )
    
    p
  }
)
```

```{r}
# save fig 05
ggsave(
  plot = plots_evo[["default"]],
  filename = "figures/fig_05.png",
  height = 120, width = 120, units = "mm"
)

# save supplementary figure for percent costs
ggsave(
  plot = plots_evo[["percent"]],
  filename = "supplement/figures/fig_evo_change_percent_cost.png",
  height = 120, width = 120, units = "mm"
)

# save supplementary figure for global dispersal
ggsave(
  plot = plots_evo[["global"]],
  filename = "supplement/figures/fig_evo_change_global_dispersal.png",
  height = 120, width = 120, units = "mm"
)
```

## Compare movement, intake, and associations

```{r}
# list files, read, and filter for default model options
files = list.files(
  "data/results/gen_data", 
  pattern = "csv",
  full.names = TRUE
)

data_all = lapply(files, fread)
data_all = rbindlist(data_all)

data = data_all
# data = data[!((cost == 0.1) & (infect_percent))]

# plot regen as rate per generation timesteps
data[, regen_r := gen_time / regen]
g_bin = 50
data[, gen_bin := floor(gen / g_bin) * g_bin]

# handle main types of simulation: default, percent, and global
data[, sim_type := fcase(
  infect_percent == T, "percent",
  dispersal == 10, "global",
  dispersal == 2, "default"
)]

# get time since pathogen
sgen = 3000
genmax = 5000
data[, gen_abs := gen_bin - sgen]

# focus on generations before and after spillover
data[, gen_abs := fifelse(
  abs(gen - sgen) < g_bin, gen - sgen, gen_abs
)]

# split by simulation type
data = split(
  data,
  by = "sim_type"
)
```

```{r}
plots_eco = lapply(
  data,
  function(df) {
    
    df = melt(
      df[, c("intake.mean", "moved.mean", "assoc.mean",
             "gen_abs", "cost", "regen_r", "repl")],
      id.vars = c("gen_abs", "cost", "regen_r", "repl")
    )
    
    df[, value := value / (max(value)), by = c("cost", "regen_r", "variable")]
    
    ggplot(df)+
      stat_summary(
        aes(
          gen_abs, value,
          group = variable,
          col = variable
        ),
        geom = "line"
      )+
      stat_summary(
        aes(
          gen_abs, value,
          group = variable,
          col = variable
        ),
        size = 0.5,
        geom = "point"
      )+
      geom_vline(
        xintercept = c(0, 25),
        lty = 2,
        size = 0.3,
        col = rep(c("red", "grey"), 9)
        # col = c("grey", "black", "grey")
      )+
      scale_colour_discrete_diverging(
        palette = "Tofino", 
        l1 = 50, c1 = 80,
        order = c(3, 1, 2),
        name = NULL,
        labels = c(
          "Mean per-capita intake",
          "Mean distance moved",
          "Mean encounters w/ other individuals"
        )
      )+
      scale_x_continuous(
        trans = ggallin::pseudolog10_trans,
        breaks = c(sgen, genmax) - sgen,
        labels = scales::comma(
          x = c(sgen, genmax),
          prefix = "G = "
        ),
        name = "Increasing productivity (social information less useful) \u279c",
        sec.axis = dup_axis(
          breaks = c(-25, 0, 25),
          labels = c(-25, 0, 25),
          name = "Gens since patho. intro."
        )
      )+
      scale_y_continuous(
        labels = scales::percent,
        breaks = NULL,
        name = glue::glue("Increasing disease cost \u279c"),
        sec.axis = dup_axis(
          breaks = c(0, 0.5, 1),
          labels = scales::percent,
          name = "% Variable value"
        )
      )+
      facet_grid(
        cost ~ regen_r,
        as.table = F, 
        switch = c("both"),
        labeller = labeller(
          cost = function(x) {
            if(x >= 0.1) {
              sprintf("δE = %s", x)
            } else {
              scales::percent(as.numeric(x), prefix = "δE = ")
            }
          },
          regen_r = function(x) sprintf("R = %s times/gen", x)
        )
      )+
      coord_cartesian(
        expand = T
      )+
      theme_test(
        base_size = 8, 
        base_family = "Arial"
      )+
      theme(
        legend.position = "top", 
        legend.key.height = unit(1, "mm"),
        strip.placement = "outside",
        strip.text = ggtext::element_markdown(),
        axis.text.x = element_text(hjust = 0.5, size = 6)
      )+
      guides(
        colour = guide_legend(
          override.aes = list(
            size = 2
          )
        )
      )
  }
)
```

```{r}
# save figures for supplementary material
Map(
  plots_eco, names(plots_eco),
  f = function(p, n) {
    ggsave(
      p,
      filename = glue("supplement/figures/fig_eco_change_{n}.png"),
      width = 120,
      height = 120,
      units = "mm"
    )
  }
)
```

