---
editor_options: 
  chunk_output_type: console
---

# Plot networks and SIR models

```{r}
library(data.table)
library(ggplot2)

library(patchwork)
library(colorspace)
```

## Spillover

```{r}
# spillover data and rounding
popsize = 500
data_sir_models = fread("data/results/data_sir_models.csv")

# data_sir_models$mean = data_sir_models$mean / 500
data_sir_models = data_sir_models[class == "NR" & gamma == 1 &
                                    beta == 5 & threshold %in% c(1, 10) ]

# select scenario
data_sir_models = data_sir_models[regen == 50 & cost == 0.25]

data_sir_models[, tround := plyr::round_any(time, 0.25)]
data_sir_models[, type := factor(type, levels = c("pre", "post"))]
```

```{r}
data_sir_models = split(data_sir_models, by = "threshold")
```


```{r}
plot_sir_models =
lapply(data_sir_models, function(df) {
  ggplot(df)+
    geom_hline(
      yintercept = 0.5,
      col = "grey",
      lty = 2
    )+
    geom_bin2d(
      aes(
        time, mean / popsize,
        fill = type,
        alpha = ..density..
      ),
      show.legend = F
    )+
    stat_summary(
      fun = mean,
      fun.max = ci_upper,
      fun.min = ci_lower,
      aes(
        tround, mean / popsize, 
        colour = type,
        shape = type,
        group = interaction(type, threshold, beta)
      ),
      stroke = 0.8,
      size = 0.3,
      position = position_dodge(width = 0.1)
    )+
    # facet_grid(
    #   rows = vars(beta),
    #   # cost ~ regen,
    #   labeller = labeller(
    #     class = c(
    #       "NI" = "Indivs. infected",
    #       "NR" = "Recovered"
    #     ),
    #     threshold = label_both
    #   )
    # )+
    scale_colour_discrete_diverging(
      l2 = 50,# l2 = 40,
      palette = "Blue-Red",
      rev = FALSE,
      # palette = "Plasma",
      breaks = c("pre", "post"),
      labels = c("Pre-pathogen intro.", "Post-pathogen intro.")
    )+
    scale_fill_discrete_diverging(
      palette = "Blue-Red",
      rev = FALSE,
      # palette = "Plasma",
      breaks = c("pre", "post"),
      labels = c("Pre-pathogen intro.", "Post-pathogen intro.")
    )+
    scale_shape_manual(
      values = c(
        "pre" = 16,
        "post" = 17
      ),
      breaks = c("pre", "post"),
      labels = c("Pre-pathogen intro.", "Post-pathogen intro.")
    )+
    scale_y_continuous(
      labels = scales::percent,
      # breaks = c(0.01, 0.33, 0.67, 1)
    )+
    scale_x_sqrt()+
    theme_test(
      base_size = 8
    )+
    theme(
      legend.position = "top",
      strip.background = element_blank(),
      strip.text = element_text(
        face = "italic"
      ),
      axis.text.y = element_text(
        angle = 90,
        hjust = 0.5,
        size = 6
      )
    )+
    coord_cartesian(
      xlim = c(0, 10),
      ylim = c(0, 1)
    )+
    labs(
      x = "SIR model simulation time",
      y = "% Agents",
      fill = NULL,
      colour = NULL,
      shape = NULL
    )
})


plot_sir_models =
  wrap_plots(
  plot_sir_models,
  guides = "collect",
  ncol = 2
) &
  plot_annotation(
    tag_levels = "A"
  ) &
  theme(
    legend.position = "bottom",
    plot.tag = element_text(
      face = "bold"
    ),
    legend.margin = margin(rep(0, 4)),
    plot.margin = margin(rep(1, 4))
  )

ggsave(
  plot_sir_models,
  filename = "figures/fig_04_new.png",
  height = 60,
  width = 110,
  units = "mm"
)
```

