---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(igraph)
library(ggraph)
library(tidygraph)
library(dplyr)
```

```{r}
load("data/output/1633784528.Rds")
gs = data[["matrices"]]
g = gs[[6]]
```

```{r}
g = igraph::graph_from_adjacency_matrix(
  g, mode = "upper", weighted = TRUE, diag = F
)
```

```{r}
# make tidygraph and add id
g = as_tbl_graph(g) %N>%
    mutate(id = 1:n())

# get attribute col
d2 = data[["gen_data"]][["pop_data"]][[250]] |> 
  as_tibble() |> 
  mutate(id = seq(length(energy)))

# rescale d2 weights
d2 = d2 |> 
  mutate(sum_wt = abs(sF) + abs(sH) + abs(sN)) |> 
  mutate(across(.cols = c("sF", "sH", "sN"), 
                .fns = function(x) { x / sum_wt }))

# join with network
g = left_join(g, d2, by = "id")
```

```{r}
g = mutate(
  g, 
  community = as.factor(group_infomap()),
  degree = degree(g),
  coreness = node_coreness(),
  centrality = centrality_betweenness()
)

d2 = as_tibble(g)
```

```{r}
ggplot(d2)+
  geom_jitter(
    aes(sF, sH, col = degree),
    # show.legend = F,
    alpha = 0.8,
    size = 3
  )+
  scale_colour_viridis_c(
    option = "A",
    trans = "sqrt",
    direction = -1
  )+
  scale_x_continuous(
    # trans = ggallin::ssqrt_trans
  )+
  scale_y_continuous(
    trans = ggallin::ssqrt_trans
  )+
  coord_cartesian(
    # xlim = c(-1, 1),
    # ylim = c(-1, 1)
  )
```

