---
editor_options: 
  chunk_output_type: console
---

# Plot social strategies

```{r}
library(data.table)
library(ggplot2)
library(patchwork)
library(colorspace)
```

Load data.

```{r}
files = list.files(path = "data/results/", pattern = "si", full.names = T)
scenario = grep(pattern = "\\d{1}", files)
```

```{r}
data = Map(files, scenario, f = function(file, sc) {
  df = fread(file)
  df$scenario = sc
  df
})

data = rbindlist(data)
# data = dcast(
#   data,
#   gen + repl + spread + scenario ~ strat_social,
#   value.var = "N"
# )
# 
# data = data[, list(
#   handler_tracking = sum(`handler tracking` + `agent tracking`) / 500,
#   agent_avoiding = `agent avoiding` / 500
# ),  by = c("gen", "repl", "scenario")]
# 
# data = melt(
#   data,
#   id.vars = c("gen", "repl", "scenario"),
#   value.name = "N",
#   variable.name = "social_strat"
# )

data_summary = copy(data)
data_summary[, gen_round := plyr::round_any(gen, 500)]
```

```{r}
labels = c(
  "1" = "Sc. 1: No pathogen",
  "2" = "Sc. 2: Endemic pathogen",
  "3" = "Sc. 3: Spillover pathogen"
)
```

## Plot social strategies

```{r}
# plot_si =
ggplot(data[gen %% 100 == 0])+
  # stat_summary(
  #   data = data_summary[
  #     strat_social %in% c("agent avoiding")
  #   ],
  #   fun = median, 
  #   fun.min = function(x) {quantile(x, 0.05)}, 
  #   fun.max = function(x) {quantile(x, 0.95)},
  #   aes(
  #     gen_round, N,
  #     colour = as.factor(strat_social),
  #     # group = interaction(social_strat, repl)
  #   ),
  #   # geom = "line",
  #   position = position_dodge(
  #     width = 200
  #   ),
  #   show.legend = T
  # )+
  geom_area(
    aes(
      gen, N,
      fill = strat_social,
      group = strat_social
    ),
    position = "stack"
  )+
  geom_vline(
    data = data.table(
      x = 0.667 * 5000,
      scenario = 3
    ),
    aes(
      xintercept = x
    ),
    lty = 2
  )+
  # scale_colour_manual(
  #   values = c("steelblue", "darkred"),
  #   labels = c("handler tracking", "agent avoiding")
  # )+
  scale_x_continuous(
    breaks = c(1, 1000, 2500, 5000),
    labels = scales::comma
  )+
  scale_y_continuous(
    # labels = scales::percent
  )+
  theme_classic(
    base_size = 10
  )+
  theme(
    strip.background = element_blank(),
    strip.text = element_text(
      face = "italic"
    ),
    panel.grid.major = element_line(
      size = 0.2
    ),
    legend.position = "bottom"
  )+
  facet_grid(
    repl~scenario,
    labeller = labeller(
      scenario = labels
    ),
    scales = "free"
  )+
  coord_cartesian(
    # ylim = c(0, 300)
  )+
  guides(
    colour = guide_legend(
      override.aes = list(
        alpha = 1,
        size = 2
      )
    )
  )+
  labs(
    x = "Generation",
    y = "% Agents",
    colour = NULL
  )
```

## Plot associations

Load data.

```{r}
files = list.files(path = "data/results/", pattern = "gen", full.names = T)
scenario = grep(pattern = "\\d{1}", files)
```

```{r}
data_assoc = Map(files, scenario, f = function(file, sc) {
  df = fread(file)
  df$scenario = sc
  df
}) |>
  rbindlist()

data_assoc_summary = copy(data_assoc)
data_assoc_summary[, gen_round := plyr::round_any(gen, 500)]
```

```{r}
plot_assoc =
  ggplot(data_assoc[gen %% 10 == 0])+
  geom_bin_2d(
    aes(
      gen, mean_assoc,
    ),
    show.legend = F,
    binwidth = c(100, 0.05)
  )+
  stat_summary(
    data = data_assoc_summary,
    fun = median,
    fun.min = function(x) {quantile(x, 0.05)}, 
    fun.max = function(x) {quantile(x, 0.95)},
    aes(
      gen_round, mean_assoc,
      # group = interaction(scenario, repl)
    ),
    # geom = "line",
    show.legend = F
  )+
  geom_vline(
    data = data.table(
      x = 0.667 * 5000,
      scenario = 3
    ),
    aes(
      xintercept = x
    ),
    lty = 2
  )+
  scale_colour_discrete_qualitative(
    palette = "Dark 2",
    order = c(3,1,2),
    l1 = 40
  )+
  scale_fill_continuous_sequential(
    palette = "Sunset"
  )+
  scale_x_continuous(
    # trans = "sqrt",
    breaks = c(1, 1000, 2500, 5000),
    labels = scales::comma
  )+
  scale_y_continuous(
    trans = "log10",
    # breaks = c(50, 1000, 2500, 5000),
    labels = scales::comma
  )+
  facet_wrap(
    ~scenario,
    labeller = labeller(
      scenario = labels
    ),
    scales = "free"
  )+
  theme_classic(
    base_size = 10
  )+
  theme(
    strip.background = element_blank(),
    strip.text = element_text(
      face = "italic"
    ),
    panel.grid.major = element_line(
      size = 0.2
    )
  )+
  coord_cartesian(
    expand = T,
    ylim = c(50, 2000)
  )+
  labs(
    x = "Generation",
    y = "Mean per-capita encounters",
    fill = NULL
  )
```

```{r}
wrap_plots(
  plot_si,
  plot_assoc,
  ncol = 1
)
```

