---
editor_options: 
  chunk_output_type: console
---

# Plot networks and SIR models

```{r}
library(data.table)
library(ggplot2)

library(patchwork)
library(colorspace)
```

```{r}
labels = c(
  "nopatho" = "Sc. 1: No pathogen",
  "endemic" = "Sc. 2: Endemic pathogen",
  "spillover" = "Sc. 3: Spillover pathogen"
)
```

## Basic scenarios

```{r}
sir_basic = fread("data/results/data_sir_basic.csv")
# sir_basic$mean = sir_basic$mean / 500
sir_basic = sir_basic[class != "NS" & gamma == 1 & 
                        beta == 1 & threshold %in% c(1, 10) ]
sir_basic[, tround := plyr::round_any(time, 0.2)]
sir_basic$scenario = factor(sir_basic$scenario, 
                            levels = c("nopatho", "endemic"))
```

```{r}
sir_plot_basic = 
  sir_basic %>% 
  ggplot()+
  stat_summary(
    aes(
      tround, mean/500, 
      col = scenario,
      shape = scenario
    ),
    alpha = 0.8
  )+
  facet_grid(
    threshold ~ class,
    labeller = labeller(
      class = c(
        "NI" = "Infected",
        "NR" = "Recovered"
      ),
      threshold = label_both
    )
  )+
  scale_colour_manual(
    values = c(
      "nopatho" = "steelblue",
      "endemic" = "brown"
    ),
    labels = c("No pathogen", "Endemic pathogen")
  )+
  scale_shape_manual(
    values = c(16, 17),
    labels = c("No pathogen", "Endemic pathogen")
  )+
  scale_y_sqrt(
    labels = scales::percent,
    breaks = c(0.01, 0.33, 0.67, 1)
  )+
  scale_x_sqrt()+
  theme_test()+
  theme(
    legend.position = "top",
    strip.background = element_blank(),
    strip.text = element_text(
      face = "italic"
    ),
    axis.text.y = element_text(
      angle = 90,
      hjust = 0.5
    ),
    panel.grid.major.y = element_line(
      # colour = "grey",
      size = 0.3,
      linetype = 2,
      color = "grey"
    )
  )+
  coord_cartesian(
    xlim = c(0, 15),
    ylim = c(0, 1)
  )+
  labs(
    x = "SIR model simulation time",
    y = "% Agents",
    colour = NULL,
    shape = NULL
  )
```


## Spillover

```{r}
# spillover data and rounding
sir_spillover = fread("data/results/data_sir_spillover.csv")
# sir_spillover$mean = sir_spillover$mean / 500
sir_spillover = sir_spillover[class != "NS" & gamma == 1 & 
                        beta == 1 & threshold %in% c(1, 10) ]
sir_spillover[, tround := plyr::round_any(time, 0.2)]
sir_spillover[, type := factor(type, levels = c("pre", "post"))]
```

```{r}
plot_sir_spillover = 
  sir_spillover %>% 
  ggplot()+
  stat_summary(
    aes(
      tround, mean/500, 
      col = type,
      shape = type
    ),
    alpha = 0.8
  )+
  facet_grid(
    threshold ~ class,
    labeller = labeller(
      class = c(
        "NI" = "Infected",
        "NR" = "Recovered"
      ),
      threshold = label_both
    )
  )+
  scale_colour_manual(
    values = c(
      "pre" = "steelblue",
      "post" = "brown"
    ),
    breaks = c("pre", "post"),
    labels = c("Pre-spillover", "Post-spillover")
  )+
  scale_shape_manual(
    values = c(16, 17),
    breaks = c("pre", "post"),
    labels = c("Pre-spillover", "Post-spillover")
  )+
  scale_y_sqrt(
    labels = scales::percent,
    breaks = c(0.01, 0.33, 0.67, 1)
  )+
  scale_x_sqrt()+
  theme_test()+
  theme(
    legend.position = "top",
    strip.background = element_blank(),
    strip.text = element_text(
      face = "italic"
    ),
    axis.text.y = element_text(
      angle = 90,
      hjust = 0.5
    ),
    panel.grid.major.y = element_line(
      # colour = "grey",
      size = 0.3,
      linetype = 2,
      color = "grey"
    )
  )+
  coord_cartesian(
    xlim = c(0, 15),
    ylim = c(0, 1)
  )+
  labs(
    x = "SIR model simulation time",
    y = "% Agents",
    colour = NULL,
    shape = NULL
  )
```

```{r}
ggsave(
  plot_sir_spillover,
  filename = "figures/fig_05.png",
  height = 120,
  width = 120,
  units = "mm"
)
```

