---
editor_options: 
  chunk_output_type: console
---

# Plot intake and movement outcomes

```{r}
library(data.table)
library(forcats)

library(ggplot2)
library(patchwork)
library(colorspace)
```

Load data.

```{r}
data = fread("data/results/data_gen.csv")
data[, scenario := fcase(
  scenario == "nopatho", 1,
  scenario == "endemic", 2,
  scenario == "spillover", 3
)]
data[, gen_round := plyr::round_any(gen, 500)]

# melt data
data_melt = data[, c("gen_round", "scenario",
                     "energy.mean", "intake.mean")] |>
  melt(
    id.vars = c("gen_round", "scenario")
  )

# no disease in sc 1
data_melt = data_melt[!(
  (variable %in% c("energy.mean")) &
    (scenario == 1)
)]
# handle sc 3
data_melt = data_melt[!(
  (variable %in% c("energy.mean")) &
    (scenario == 3) & (gen_round < 3334)
)]
```

```{r}
labels = c(
  "1" = "Sc. 1: No pathogen",
  "2" = "Sc. 2: Endemic pathogen",
  "3" = "Sc. 3: Spillover pathogen"
)
```

## Plot intake

```{r}
plot_intake =
  ggplot(data)+
  stat_summary(
    data = data_melt,
    fun = mean,
    fun.min = function(x) {quantile(x, 0.05)},
    fun.max = function(x) {quantile(x, 0.95)},
    aes(
      gen_round, value,
      shape = variable,
      col = variable
    ),
    show.legend = T,
    position = position_dodge(
      width = 100
    )
  )+
  geom_hline(
    yintercept = 0,
    col = "grey",
    lty = 2
  )+
  geom_vline(
    data = data.table(
      x = 0.667 * 5000,
      scenario = 3
    ),
    aes(
      xintercept = x
    ),
    lty = 2
  )+
  scale_colour_discrete_qualitative(
    palette = "Dark 3",
    labels = c("Net energy", "Total intake"),
    name = NULL,
    l1 = 40
  )+
  scale_shape_manual(
    values = c(17, 16),
    labels = c("Net energy", "Total intake"),
    name = NULL
  )+
  scale_x_continuous(
    # trans = "sqrt",
    breaks = c(1, 1000, 2500, 5000),
    labels = scales::comma
  )+
  scale_y_continuous(
    # trans = ggallin::ssqrt_trans
  )+
  facet_wrap(
    vars(scenario),
    labeller = labeller(
      scenario = labels
    ),
    scales = "free"
  )+
  theme_classic(
    base_size = 10
  )+
  theme(
    strip.background = element_blank(),
    strip.text = element_text(
      face = "italic"
    ),
    legend.background = element_blank(),
    legend.position = c(0.1, 0.2),
    panel.grid.major.y = element_line(
      size = 0.2
    )
  )+
  coord_cartesian(
    ylim = c(0, 15)
  )+
  labs(
    x = "Generation",
    y = "Mean per-capita value"
  )
```

## Plot movement

```{r}
plot_movement =
  ggplot(data)+
  stat_summary(
    # data = data_melt,
    fun = mean, 
    fun.min = function(x) {quantile(x, 0.05)}, 
    fun.max = function(x) {quantile(x, 0.95)},
    aes(
      gen_round, moved.mean,
      # colour = as.factor(scenario),
      # group = interaction(scenario, repl)
    ),
    # position = position_jitter(),
    show.legend = F,
    colour = "navy",
    shape = 15
  )+
  geom_vline(
    data = data.table(
      x = 0.667 * 5000,
      scenario = 3
    ),
    aes(
      xintercept = x
    ),
    lty = 2
  )+
  scale_x_continuous(
    # trans = "sqrt",
    breaks = c(1, 1000, 2500, 5000),
    labels = scales::comma
  )+
  facet_wrap(
    ~scenario,
    labeller = labeller(
      scenario = labels
    ),
    scales = "free"
  )+
  theme_classic(
    base_size = 10
  )+
  theme(
    strip.background = element_blank(),
    strip.text = element_text(
      face = "italic"
    ),
    panel.grid.major.y = element_line(
      size = 0.2
    )
  )+
  coord_cartesian(
    ylim = c(35, 90),
  )+
  labs(
    x = "Generation",
    y = "Mean distance moved"
  )
```

## Make Figure 1

```{r}
fig_1 =
wrap_plots(
  plot_intake, 
  plot_movement,
  ncol = 1
) &
  plot_annotation(
    tag_levels = c("A", 1)
  ) &
  theme(
    plot.tag = element_text(
      face = "bold",
      size = 10
    )
  )

ggsave(
  fig_1,
  filename = "figures/fig_01.png",
  height = 5,
  width = 6
)
```

